# Generated by Django 5.1.3 on 2025-02-26 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategic_planning', '0002_initial_load_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
    ]
